name: Build NeoBirch (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: x64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install conan
        run: |
          pip install conan

      - name: Cache Conan Dependencies
        id: cache-conan
        uses: actions/cache@v4
        with:
          path: ${{ env.USERPROFILE }}\.conan2
          key: ${{ hashFiles('**/conanfile.txt') }}
      - if: ${{steps.cache-conan.outputs.cache-hit != 'true'}}
        name: Create default Conan profile
        run: conan profile detect

      - name: Install dependencies
        run: conan install . --build=missing --output-folder build -c tools.cmake.cmaketoolchain:generator=Ninja

      - name: Set up MSVC environment variables
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64
      
      - name: Configure CMake
        run: cmake --preset conan-release

      - name: Inspect Conan output
        run: dir build

      - name: Build (Windows)
        run: cmake --build build --preset conan-release
